##  Plugin Information  ##
name: PistonJump
version: 0.1
main: syam.PistonJump.PistonJump
description: Jump higher on the piston!
website: http://sakura-server.net/
##  Original Author     ##
author: syam